---
name: Sample123
description: "Rule which sends an email when an email from johndoe@gmail.com is received"
pack: angela_pack
enabled: true
trigger:
  type: angela_pack.imap.message
  parameters: {}
criteria:
  trigger.subject:
    pattern: vm create
    type: contains
action:
  ref: angela_pack.vm_workflow
  parameters: 
    Group_Name: '{{trigger.group}}'
    Location: '{{trigger.location}}'
    VM_Name: '{{trigger.vmname}}'
