---
name: Sample123
description: "Rule which sends an email when an email from johndoe@gmail.com is received"
pack: angela_pack
enabled: true
trigger:
  type: angela_pack.imap.message
  parameters: {}
criteria:
  trigger.subject:
    pattern: vm create
    type: contains
action:
  ref: core.local
  parameters:
   cmd: echo "{{trigger.sub_id}}"
